### PR TITLE
Fix Spark Kubernetes Kernel Restart issue

### LINKED ISSUE #1012: Wrong Kernel Pod IP being assigned on Kernel Restart on K8s runtime
## Description
We have deployed JEG on Kubernetes cluster and trying to run `spark_python_kubernetes` and `python_kubernetes` kernel using it. We are seeing an issue with Kernel restart operation for `spark_python_kubernetes`:

1. On Kernel restart, we see an intermittent issue where JEG does not connect to the New Kernel Driver Pods and rather registers one of the executor / driver pods from previous session if still available. This leads to kernel restart failure as all the further communication with the Kernel happens with the wrong Pod IP and it times out. 
2. Further, when we ( from Notebook UI) sends `shutdown` request for the same kernel, that too fails if a executor IP gets assigned in the above scenario.

**Upon debugging further and looking at the logs,** I found that the `label_selector` that is   being used in code to select the Kernel Driver Pods has issue incase of `spark_*` kernels .   The code only uses `kernel_id=k123` to select kernel pods which ends up selecting all the driver and executor pod running with that `kernel_id` and the first object from the list gets selected as Kernel Pod. This creates randomness and sometimes executor or previous driver pod gets selected if its not deleted yet. 
[KubernetesProcessProxy:get_container_status()](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/services/processproxies/k8s.py#L61) Code Block.
The issue does not seem to happen on `python_kubernetes` kernel as its a single pod kernel.

### How does the driver and executor get the labels?
- Its coming from the kernel spec file: [kernel.json](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kernelspecs/spark_python_kubernetes/kernel.json#L15)

```
"env": {
    "SPARK_HOME": "/opt/spark",
    "SPARK_OPTS": "--master k8s://https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT} --deploy-mode cluster 
    --name ${KERNEL_USERNAME}-${KERNEL_ID} --conf spark.kubernetes.namespace=${KERNEL_NAMESPACE} --conf spark.kubernetes.driver.label.app=enterprise-gateway     --conf spark.kubernetes.executor.label.component=kernel        --conf spark.kubernetes.driver.label.component=kernel 
 *# Driver and executor labels added. >>>>>>>>>>>>>*
    --conf spark.kubernetes.driver.label.app=enterprise-gateway
    --conf spark.kubernetes.driver.label.kernel_id=${KERNEL_ID} 

    
    --conf spark.kubernetes.executor.label.app=enterprise-gateway
    --conf spark.kubernetes.executor.label.kernel_id=${KERNEL_ID} 

        --conf spark.kubernetes.driver.container.image=${KERNEL_IMAGE} --conf spark.kubernetes.executor.container.image=${KERNEL_EXECUTOR_IMAGE} 
    --conf spark.kubernetes.authenticate.driver.serviceAccountName=${KERNEL_SERVICE_ACCOUNT_NAME} --conf spark.kubernetes.submission.waitAppCompletion=false --conf spark.kubernetes.pyspark.pythonVersion=3 ${KERNEL_EXTRA_SPARK_OPTS}",
    "LAUNCH_OPTS": ""
  },
```
**Both driver and executor pods have `kernel_id` label assigned.**

## Screenshots / Logs

Here are the details of a Kernel with ID: `3e7112ea-a104-4c76-bb08-3c2ef96f9325:d01bc549-19c37ab9f89058da4840ffe7` for which I have captured the detailed logs. 

### Kernel Pod Details
```
# old kernel pods.
name                         
k3e7112ea-a104-4c76-bb08-3c2ef96f9325-17cb3c7d0f61e624-exec-3   1/1     Running     0          87m     192.168.113.139   ip-192-168-127-71.us-west-2.compute.internal    <none>           <none>
k3e7112ea-a104-4c76-bb08-3c2ef96f9325-17cb3c7d0f61e624-exec-4   1/1     Running     0          87m     192.168.101.128   ip-192-168-101-31.us-west-2.compute.internal    <none>           <none>
# old kernel driver pod
*k3e7112ea-a104-4c76-bb08-3c2ef96f9325-8103d17d0f5b41c2-driver   0/2     Completed   0          95m     192.168.145.81*    ip-192-168-152-96.us-west-2.compute.internal    <none>           <none>

# new Kernel upon restart
*k3e7112ea-a104-4c76-bb08-3c2ef96f9325-c439d27d0f61b0b4-driver   2/2     Running     0          88m     192.168.111.104*   ip-192-168-110-92.us-west-2.compute.internal    <none>           <none>
```
From the above output: 
- Old driver IP: 192.168.145.81
- new driver IP: 192.168.111.104

### JEG logs with inline comments:

```
<<<<<<<<<<<<<<<<<<<<<<<<<<<# closing existing connection with the Kernel

[D 2021-11-11 14:23:15.715 EnterpriseGatewayApp] Websocket closed 3e7112ea-a104-4c76-bb08-3c2ef96f9325:d01bc549-19c37ab9f89058da4840ffe7
[I 2021-11-11 14:23:15.716 EnterpriseGatewayApp] Starting buffering for 3e7112ea-a104-4c76-bb08-3c2ef96f9325:d01bc549-19c37ab9f89058da4840ffe7
[D 2021-11-11 14:23:15.716 EnterpriseGatewayApp] Clearing buffer for 3e7112ea-a104-4c76-bb08-3c2ef96f9325

<<<<<<<<<<<<<<<<<<<<<<<<<<<# restart request initiated..*
[D 2021-11-11 14:23:16.727 EnterpriseGatewayApp] Shutdown request sent to listener via gateway communication port.
[D 2021-11-11 14:23:17.828 EnterpriseGatewayApp] KubernetesProcessProxy.terminate_container_resources, pod: rhgoyal-endpoint.k3e7112ea-a104-4c76-bb08-3c2ef96f9325-6442437d0f5b75ba-exec-1, kernel ID: 3e7112ea-a104-4c76-bb08-3c2ef96f9325 has been terminated.
[D 2021-11-11 14:23:17.830 EnterpriseGatewayApp] Shutdown request sent to listener via gateway communication port.
# old kernel shutdown completed in 2 secconds..

<<<<<<<<<<<<<<<<<<<<<<<<<<< # Starting new kernel for the same Kernel IP

[D 2021-11-11 14:23:17.830 EnterpriseGatewayApp] Instantiating kernel 'PySpark (Kubernetes)' with process proxy: enterprise_gateway.services.processproxies.k8s.KubernetesProcessProxy
[D 2021-11-11 14:23:17.831 EnterpriseGatewayApp] Response socket launched on '192.168.109.162:58043' using 5.0s timeout
[D 2021-11-11 14:23:17.831 EnterpriseGatewayApp] Starting kernel: ['/usr/local/share/jupyter/kernels/spark_python_kubernetes/bin/run.sh', '--RemoteProcessProxy.kernel-id', '3e7112ea-a104-4c76-bb08-3c2ef96f9325', '--RemoteProcessProxy.response-address', '192.168.109.162:58043', '--RemoteProcessProxy.spark-context-initialization-mode', 'lazy']


# <<<<<<<<<<<<<<<<<<<<<<<<<<< waiting on kernel pod status -> picks up an executor Pod
[D 2021-11-11 14:23:18.388 EnterpriseGatewayApp] 1: Waiting to connect to k8s pod in namespace 'rhgoyal-endpoint'. Name: 'k3e7112ea-a104-4c76-bb08-3c2ef96f9325-6442437d0f5b75ba-exec-2', Status: 'Pending', Pod IP: 'None', KernelID: '3e7112ea-a104-4c76-bb08-3c2ef96f9325'

<<<<<<<< # still waiting  : Picks up a different executor-pod but this pod satisfied the `Running` state criteria

[D 2021-11-11 14:23:27.797 EnterpriseGatewayApp] 9: Waiting to connect to k8s pod in namespace 'rhgoyal-endpoint'. Name: 'k3e7112ea-a104-4c76-bb08-3c2ef96f9325-17cb3c7d0f61e624-exec-3', Status: 'Running', Pod IP: '192.168.113.139', KernelID: '3e7112ea-a104-4c76-bb08-3c2ef96f9325'

# since the pod is in running state, JEG registers this Pod's IP as new kernel IP.

[D 2021-11-11 14:23:30.574 EnterpriseGatewayApp] Received Payload 'Si9wEwPae5nBdejXkeqhaKffw5lGaZYy7t1FXlkGBYhfFuKNq843lLvHgrP642qJFzFmEY7bxyHN3gnDtEideEk0FRs4xZ4Dt51am7VCykgeE3wu8fQKu20TpCC6Dn4S+Oe0izrnHzACRLAEzEs+72s484v4IoZj5TsLzRvODB233IeDK2Sm64Yy3NrYmPA2EDR04dseKpJvz7LAPQ+g5RKutWoF6EonizIPA9TTQKv8kO24EE6y31bdkxqu9TPu/z+DY18IW+OH84snfJ1WPQt7dZV2RsJ9TBZutQjkXtNVdYloUZUHisKrkEnTFrvq1lvNRqPtrZ8pwLJ7ka4tIQtyNTVyJaFXKksgHr8LWeQUn4eIIB9NNaJb63a+RgWm8y1WX3p10BDp+jhjOk89tg=='
[D 2021-11-11 14:23:30.574 EnterpriseGatewayApp] Decrypted Payload '{"shell_port": 33285, "iopub_port": 33065, "stdin_port": 34047, "control_port": 55775, "hb_port": 45715, "ip": "0.0.0.0", "key": "32c3b119-b841-49f6-8f21-4d7957df4465", "transport": "tcp", "signature_scheme": "hmac-sha256", "kernel_name": "", "pid": "64", "pgid": "20", "comm_port": 43135}'
[D 2021-11-11 14:23:30.575 EnterpriseGatewayApp] Connect Info received from the launcher is as follows '{'shell_port': 33285, 'iopub_port': 33065, 'stdin_port': 34047, 'control_port': 55775, 'hb_port': 45715, 'ip': '0.0.0.0', 'key': '32c3b119-b841-49f6-8f21-4d7957df4465', 'transport': 'tcp', 'signature_scheme': 'hmac-sha256', 'kernel_name': '', 'pid': '64', 'pgid': '20', 'comm_port': 43135}'
[D 2021-11-11 14:23:30.575 EnterpriseGatewayApp] Host assigned to the Kernel is: 'k3e7112ea-a104-4c76-bb08-3c2ef96f9325-17cb3c7d0f61e624-exec-3' '192.168.113.139'
[D 2021-11-11 14:23:30.575 EnterpriseGatewayApp] Established gateway communication to: 192.168.113.139:43135 for KernelID '3e7112ea-a104-4c76-bb08-3c2ef96f9325'
[D 2021-11-11 14:23:30.575 EnterpriseGatewayApp] Updated pid to: 64
[D 2021-11-11 14:23:30.576 EnterpriseGatewayApp] Updated pgid to: 20
[D 2021-11-11 14:23:30.577 EnterpriseGatewayApp] Received connection info for KernelID '3e7112ea-a104-4c76-bb08-3c2ef96f9325' from host 'k3e7112ea-a104-4c76-bb08-3c2ef96f9325-17cb3c7d0f61e624-exec-3': {'shell_port': 33285, 'iopub_port': 33065, 'stdin_port': 34047, 'control_port': 55775, 'hb_port': 45715, 'ip': '192.168.113.139', 'key': '32c3b119-b841-49f6-8f21-4d7957df4465', 'transport': 'tcp', 'signature_scheme': 'hmac-sha256', 'kernel_name': '', 'comm_port': 43135}...
[D 2021-11-11 14:23:30.577 EnterpriseGatewayApp] Connecting to: tcp://192.168.113.139:55775
[D 2021-11-11 14:23:30.578 EnterpriseGatewayApp] Connecting to: tcp://192.168.113.139:33065
[D 2021-11-11 14:23:30.581 EnterpriseGatewayApp] Refreshing kernel session for id: 3e7112ea-a104-4c76-bb08-3c2ef96f9325
[I 2021-11-11 14:23:30.581 EnterpriseGatewayApp] Kernel restarted: 3e7112ea-a104-4c76-bb08-3c2ef96f9325
[D 2021-11-11 14:23:30.581 EnterpriseGatewayApp] Connecting to: tcp://192.168.113.139:33285
[D 2021-11-11 14:23:30.583 EnterpriseGatewayApp] Buffering msg on 3e7112ea-a104-4c76-bb08-3c2ef96f9325:iopub
[D 2021-11-11 14:23:30.585 EnterpriseGatewayApp] Buffering msg on 3e7112ea-a104-4c76-bb08-3c2ef96f9325:iopub
[D 2021-11-11 14:23:30.594 EnterpriseGatewayApp] Buffering msg on 3e7112ea-a104-4c76-bb08-3c2ef96f9325:iopub
[D 2021-11-11 14:23:30.595 EnterpriseGatewayApp] Buffering msg on 3e7112ea-a104-4c76-bb08-3c2ef96f9325:iopub


# here it gets interesting...timeout occurns ..no the activity status log line either.

[W 2021-11-11 14:23:35.584 EnterpriseGatewayApp] Timeout waiting for kernel_info_reply: 3e7112ea-a104-4c76-bb08-3c2ef96f9325
[E 2021-11-11 14:23:35.585 EnterpriseGatewayApp] Exception restarting kernel
    Traceback (most recent call last):
      File "/emr/notebook-env/lib/python3.7/site-packages/notebook/services/kernels/handlers.py", line 83, in post
        yield maybe_future(km.restart_kernel(kernel_id))
      File "/emr/notebook-env/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/emr/notebook-env/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/emr/notebook-env/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 345, in restart_kernel
        yield future
      File "/emr/notebook-env/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
    tornado.util.TimeoutError: Timeout waiting for restart
 # returning timeout to NB with 500 statu scode.
[E 211111 14:23:35 web:2243] 500 POST /api/kernels/3e7112ea-a104-4c76-bb08-3c2ef96f9325/restart (127.0.0.1) 18901.99ms

```

## Environment

- Enterprise Gateway Version [v2.1.0]
- Platform:  Kubernetes]
- Others [Jupyter Notebook]

## Proposed Solutions
Based on the analysis, I propose the following solutions to fix the problem and we can discuss which one aligns better both in terms on maintenance and compatibility:

### 1. Remove `kernel_id` label from Executor pods
This could be a simple fix so that JEG does not end up selecting the Executor pods when trying to filter the kernel pods. 
Cons:
1. This will break backward incompatibility of JEG. 
2.  People might have build other solutions based on these labels to track metrics related to a particular kernel session.
Thus, removing the existing label does not seem like a good idea. 

### 2. Introduce a new Label:
We could introduce a new label which will be added only to: say 
```
kernel-component: main-kernel
```
1. Spark Driver pods and not executor pods. `--conf spark.kubernetes.driver.label.kernel-component=main-kernel`
2. All the singe pod vanilla language kernels like python,R and scala etc.  ( [needs updating template file](https://github.com/jupyter/enterprise_gateway/blob/9719e6f9641d42013839ea4311cdfd6147a98e5c/etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml.j2))

To keep the code backward compatible, we can introduce a new Environment variable though which this new label 
will be made available to JEG runtime. 
```
EG_K8S_EXTRA_KERNEL_LABELS="kernel-component=main-kernel"
```
The code on `KubernetesProcessProxy:get_container_status()` can check if this environment variable is available and append to the `label_selector` parameter. 

or we can update the existing `label_selector` to hardcode this new label in code.

@kevin-bates and others: let me know your thoughts on this and I could start working on the right solution. I am interested to take it up  :) 

Thanks
Rahul Goyal

### PR DESCRIPTION
**Pull request by rahul26goyal**
## Description
The changes in this PR addressed the issue raised at #1012 . **Wrong Kernel Pod IP being assigned on Kernel Restart on K8s runtime.**
Out of the Three proposed solution, [3. Modify the Existing Spark Executor label](https://github.com/jupyter/enterprise_gateway/issues/1012#issuecomment-973746273) was finalized and corresponfing changes are made in this PR. 

## Testing
Deployed the changes on my EKS cluster:
1. verified that driver continues to get the label `component=kernel` and Executors label changed from `component=kernel` to `component=worker`.
```
kubectl get pods k6cfe0fe5-7bf3-4a93-afc1-099eb587cbc6-384a477d509aa6d4-driver -o json | jq .metadata.labels
{
  "app": "enterprise-gateway",
  "component": "kernel",
  "kernel_id": "6cfe0fe5-7bf3-4a93-afc1-099eb587cbc6",
  "spark-app-selector": "spark-26c246441cd54b6890d8ab9e7ae478c9",
  "spark-role": "driver"
}

kubectl get pods k6cfe0fe5-7bf3-4a93-afc1-099eb587cbc6-9c5aa17d509ada45-exec-1 -o json | jq .metadata.labels
{
  "app": "enterprise-gateway",
  "component": "worker",
  "kernel_id": "6cfe0fe5-7bf3-4a93-afc1-099eb587cbc6",

  "spark-app-selector": "spark-26c246441cd54b6890d8ab9e7ae478c9",
  "spark-exec-id": "1",
  "spark-exec-resourceprofile-id": "0",
  "spark-role": "executor"
}
```

2. JEG no longer selects spark executor pods as kernel pods while handling kernel restart flow. To test this, I had a temp log  line added to print the `len(ret.items)`.
3. Kernel CULL timeout is also working as expected.
```
[D 2021-11-24 06:30:26.980 EnterpriseGatewayApp] Polling every 60 seconds for kernels idle > 300 seconds...
[D 2021-11-24 06:30:26.980 EnterpriseGatewayApp] kernel_id=6cfe0fe5-7bf3-4a93-afc1-099eb587cbc6, kernel_name=spark_python_kubernetes, last_activity=2021-11-24 06:24:45.244410+00:00
[W 2021-11-24 06:30:26.981 EnterpriseGatewayApp] Culling 'idle' kernel 'spark_python_kubernetes' (6cfe0fe5-7bf3-4a93-afc1-099eb587cbc6) with 0 connections due to 341 seconds of inactivity.
[D 2021-11-24 06:30:26.981 EnterpriseGatewayApp] Clearing buffer for 6cfe0fe5-7bf3-4a93-afc1-099eb587cbc6
[I 2021-11-24 06:30:26.982 EnterpriseGatewayApp] Kernel shutdown: 6cfe0fe5-7bf3-4a93-afc1-099eb587cbc6
[D 2021-11-24 06:30:26.983 EnterpriseGatewayApp] Shutdown request sent to listener via gateway communication port.
[D 2021-11-24 06:30:33.508 EnterpriseGatewayApp] Kernel is taking too long to finish, killing
[W 2021-11-24 06:30:33.548 EnterpriseGatewayApp] Unable to delete pod: {'api_version': 'v1',
     'code': None,
     'details': None,
     'kind': 'Pod',
     'message': None,
     'metadata': {'_continue': None,
                  'remaining_item_count': None,
                  'resource_version': '74889839',
                  'self_link': '/api/v1/namespaces/rhgoyal-endpoint/pods/k6cfe0fe5-7bf3-4a93-afc1-099eb587cbc6-e33d447d509df24e-driver'},
     'reason': None,
     'status': "{'phase': 'Running', 'conditions': [{'type': 'Initialized', "
               "'status': 'True', 'lastProbeTime': None, 'lastTransitionTime': "
               "'2021-11-24T06:24:30Z'}, {'type': 'Ready', 'status': 'False', "
               "'lastProbeTime': None, 'lastTransitionTime': "
               "'2021-11-24T06:30:29Z', 'reason': 'ContainersNotReady', 'message': "
               "'containers with unready status: [spark-kubernetes-driver]'}, "
               "{'type': 'ContainersReady', 'status': 'False', 'lastProbeTime': "
               "None, 'lastTransitionTime': '2021-11-24T06:30:29Z', 'reason': "
               "'ContainersNotReady', 'message': 'containers with unready status: "
               "[spark-kubernetes-driver]'}, {'type': 'PodScheduled', 'status': "
               "'True', 'lastProbeTime': None, 'lastTransitionTime': "
               "'2021-11-24T06:24:30Z'}], 'hostIP': '192.168.101.31', 'podIP': "
               "'192.168.102.158', 'podIPs': [{'ip': '192.168.102.158'}], "
               "'startTime': '2021-11-24T06:24:30Z', 'containerStatuses': "
               "[{'name': 'emr-container-fluentd', 'state': {'running': "
               "{'startedAt': '2021-11-24T06:24:32Z'}}, 'lastState': {}, 'ready': "
               "True, 'restartCount': 0, 'image': "
               "'632055474560.dkr.ecr.us-west-2.amazonaws.com/fluentd/emr-6.3.0:latest', "
               "'imageID': "
               "'docker-pullable://632055474560.dkr.ecr.us-west-2.amazonaws.com/fluentd/emr-6.3.0@sha256:1b0caa570267449a7439e378d815c81f4fc98455d94be2d50ff559e4939aa0d4', "
               "'containerID': "
               "'docker://a8976cb8b84d48d977ff64bfeebfdcb7cdbb172d28d714586b382b657f8bf83e', "
               "'started': True}, {'name': 'spark-kubernetes-driver', 'state': "
               "{'terminated': {'exitCode': 143, 'reason': 'Error', 'startedAt': "
               "'2021-11-24T06:24:33Z', 'finishedAt': '2021-11-24T06:30:29Z', "
               "'containerID': "
               "'docker://f00f54b102bee54b328af063a55f818f4d1f94b5ef144f03518517f2d10dea0e'}}, "
               "'lastState': {}, 'ready': False, 'restartCount': 0, 'image': "
               "'599320413262.dkr.ecr.us-west-2.amazonaws.com/jeg-images:gbi-custom-spark-1.3', "
               "'imageID': "
               "'docker-pullable://599320413262.dkr.ecr.us-west-2.amazonaws.com/jeg-images@sha256:1c7435a591748dada97c0fc90abddd8c918d36ab2e40b6653642ae511def84e3', "
               "'containerID': "
               "'docker://f00f54b102bee54b328af063a55f818f4d1f94b5ef144f03518517f2d10dea0e', "
               "'started': False}], 'qosClass': 'Burstable'}"}
[W 2021-11-24 06:30:33.548 EnterpriseGatewayApp] KubernetesProcessProxy.terminate_container_resources, pod: rhgoyal-endpoint.k6cfe0fe5-7bf3-4a93-afc1-099eb587cbc6-e33d447d509df24e-driver, kernel ID: 6cfe0fe5-7bf3-4a93-afc1-099eb587cbc6 has not been terminated.
[D 2021-11-24 06:30:33.595 EnterpriseGatewayApp] KubernetesProcessProxy.terminate_container_resources, pod: rhgoyal-endpoint.k6cfe0fe5-7bf3-4a93-afc1-099eb587cbc6-e33d447d509df24e-driver, kernel ID: 6cfe0fe5-7bf3-4a93-afc1-099eb587cbc6 has been terminated.
```
4. For vanilla python language kernel, the start, restart and shutdown requests are working as expected. 

Resolves #1012

### CODE REVIEW

**Comment by rahul26goyal** [comment]
@kevin-bates : When I tried running Unit tests locally, I see following 2 issue on my setup on MAC OSX.

1. issue running `make test`
```
 ➜  enterprise_gateway git:(k8-kernel-restart-issue) ✗ make test

source activate enterprise-gateway-dev && pytest -v -s  enterprise_gateway/tests
/bin/bash: activate: No such file or directory
make: *** [test] Error 1
```

2. To overcome above issue, I ran the `pytest` command directly and I see 13 test failure both on master and my private branch. Are these failure expected?

```
# ➜ enterprise_gateway git:(k8-kernel-restart-issue) ✗ pytest -v -s  enterprise_gateway/tests

============================================ test session starts =============================================
platform darwin -- Python 3.9.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/rhgoyal/miniconda3/envs/enterprise-gateway-dev-oss/bin/python
cachedir: .pytest_cache
rootdir: /Users/rhgoyal/learning/github-repos/enterprise_gateway
plugins: tornasync-0.6.0.post2, anyio-3.4.0
collected 54 items                                          
-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================== short test summary info ===========================================
FAILED enterprise_gateway/tests/test_enterprise_gateway.py::TestEnterpriseGateway::test_authorization - tor...
FAILED enterprise_gateway/tests/test_enterprise_gateway.py::TestEnterpriseGateway::test_kernel_id_env_var
FAILED enterprise_gateway/tests/test_enterprise_gateway.py::TestEnterpriseGateway::test_max_kernels_per_user
FAILED enterprise_gateway/tests/test_enterprise_gateway.py::TestEnterpriseGateway::test_port_range - tornad...
FAILED enterprise_gateway/tests/test_handlers.py::TestDefaults::test_auth_token - AssertionError: 500 != 201
FAILED enterprise_gateway/tests/test_handlers.py::TestDefaults::test_crud_sessions - tornado.httpclient.HTT...
FAILED enterprise_gateway/tests/test_handlers.py::TestDefaults::test_get_kernels - tornado.httpclient.HTTPC...
FAILED enterprise_gateway/tests/test_handlers.py::TestDefaults::test_kernel_comm - tornado.httpclient.HTTPC...
FAILED enterprise_gateway/tests/test_handlers.py::TestDefaults::test_kernel_defaults - tornado.httpclient.H...
FAILED enterprise_gateway/tests/test_handlers.py::TestDefaults::test_kernel_env - tornado.httpclient.HTTPCl...
FAILED enterprise_gateway/tests/test_handlers.py::TestDefaults::test_kernel_env_auth_token - UnboundLocalEr...
FAILED enterprise_gateway/tests/test_handlers.py::TestDefaults::test_max_kernels - tornado.httpclient.HTTPC...
FAILED enterprise_gateway/tests/test_handlers.py::TestWildcardEnvs::test_kernel_wildcard_env - tornado.http...
================================= 13 failed, 41 passed, 4 warnings in 4.33s ====================
```

**Review by kevin-bates — COMMENTED** [review]
@rahul26goyal - these changes look good.  I think a similar change is required in https://github.com/jupyter/enterprise_gateway/blob/master/etc/kernelspecs/spark_R_kubernetes/kernel.json.

Regarding the tests, it looks like you don't have `conda` installed in your path since `activate` appears to be missing.  You can try setting that up, although we really don't have any tests that would exercise these changes, so, as long as you're seeing the expected behaviors in your runtime/test environment, that's what's important.

Thanks.

**Comment by rahul26goyal** [comment]
thanks for reviewing the PR @kevin-bates . 
I have made the changes in the `R spec` file too. As updated the in the PR description, I have done the testing and it seems to be working as expected.

**Review by kevin-bates — APPROVED** [review]
Thanks @rahul26goyal - this looks good.  

Once you're ready, please update the title to not include `[WIP]` and we'll move this forward.

**Comment by rahul26goyal** [comment]
done @kevin-bates . We are good to merge  from my side.

**Comment by kevin-bates** [comment]
Thank you @rahul26goyal - this is a nice update.

**Pull request merged**
