### PR TITLE
Update to python3 and use version agnostic conda paths

### PR DESCRIPTION
**Pull request by akchinSTC**
- Update miniconda / python to version 3
- Use /opt/conda as installation prefix for miniconda

### CODE REVIEW

**Comment by lresende** [comment]
@akchinSTC Do you want to merge #587 and take issue #573 ?

**Comment by akchinSTC** [comment]
@lresende - copy that, assigned the issue to me and will merge your changes in with my PR and close both.

**Comment by kevin-bates** [comment]
FWIW, I setup a python 3 env on my python 2.7 YARN cluster today.  

My base (python 2) configuration was located in `/opt/anaconda2`.  I then created a python 3 environment:
```
conda create --name py3 python=3.6
```
I then switched users (su) to the gateway user and switched envs to `py3`:
```
source /opt/anaconda2/bin/activate py3  (I could also use `conda activate py3`)
```
I then updated the start script for EG to remove the fully-qualified path prefix on the `jupyter` command so that it used that from the current env.  Then launched EG.

For those kernels that require python 2, I added the following to their `run.sh` scripts prior to the spark-submit call to switch back to python 2
```
source /opt/anaconda2/bin/activate base
```
I also added `source /opt/anaconda2/bin/deactivate` to the end of `run.sh`.

I was then able to launch a python kernel in YARN cluster mode.  Had the environment not be switched, python syntax errors will be produced from `/bin/hdp-select` since it doesn't use parentheses on its print statements.

**Comment by lresende** [comment]
This has been merged to the [remove-python-2.x](https://github.com/jupyter/enterprise_gateway/tree/remove-python-2.x) branch for team collaboration.

**Pull request closed without merging**
