### PR TITLE
Add origin restriction config

### PR DESCRIPTION
**Pull request by bgerrity**
Addressing #989: It's a fairly simple SSL check and doesn't offer any support for running without authentication. Not sure if this is the best approach; open to any feedback or alternative implementations.

### CODE REVIEW

**Review by kevin-bates — COMMENTED** [review]
@bgerrity - these changes look good and helpful - thank you.

There are some linting issues with the `authorized_origin` help string that should get fixed up, but once fixed, the default case still appears to work.

We should also update the configuration section of the docs (near `authorized_users`): https://github.com/jupyter/enterprise_gateway/blob/master/docs/source/config-options.md

Are you able to adequately test `authorized_origin` having a value?  (Sorry I'm not able to do that.)

**Comment by kevin-bates** [comment]
Thanks for the update.  Looks like a test is side-effected by this, but I'm not certain the test is that valid.

https://github.com/jupyter/enterprise_gateway/blob/d6d6ff59fb33ddb9916f1e396f5e335d5a3dc6b8/enterprise_gateway/tests/test_gatewayapp.py#L97

Seems like the test is just ensuring the SSL version.  Is there another way this could be triggered w/o a non-existent cert file?

**Comment by bgerrity** [comment]
@kevin-bates Fixed the lint and added the option to the config docs; I'll fix that unit test.

For manual testing, I enabled TLS (`--certfile`, `--keyfile`, `--client-ca`) and ran with `--EnterpriseGatewayApp.authorized_origin="localhost"` and another origin.

**Comment by bgerrity** [comment]
> Seems like the test is just ensuring the SSL version. Is there another way this could be triggered w/o a non-existent cert file?

Since the options build is being delegated to `ssl.SSLContext`, I don't think there's any need to validate it.

**Comment by kevin-bates** [comment]
> Since the options build is being delegated to ssl.SSLContext, I don't think there's any need to validate it. IMO it's best to remove the second part of that test.

I'm okay with that.  I think version 5 is the default anyway and it's configurable as well.

**Comment by bgerrity** [comment]
Cut down that unit test.

**Comment by bgerrity** [comment]
My bad for the noise, will fix that other test as well.

**Review by kevin-bates — APPROVED** [review]
Looks good Brendan - thank you!

**Pull request merged**
