### PR TITLE
Add support for Spark 3.0 and pod templates for k8s

### PR DESCRIPTION
**Pull request by kevin-bates**
EDIT: This pull request has been combined with #867 since the two overlapped.

Changes necessary to support Spark 3.0 and Spark POD Templates on Kubernetes.  This allows us to use the same
`kernel-pod.yaml` file for all k8s kernel launches.  There are some restrictions in place and many attributes must still be set via `--conf` options.

These changes also update the Apache Toree version to 0.5.0.

Resolves:  #556, #866

### CODE REVIEW

**Comment by kevin-bates** [comment]
If anyone wants to take this for a spin, here are some images that can be used...
[kbates/enterprise-gateway:3.0.0.4c1cd80](https://cloud.docker.com/repository/docker/kbates/enterprise-gateway)
[kbates/kernel-spark-py:3.0.0.4c1cd80](https://cloud.docker.com/repository/docker/kbates/kernel-spark-py)

Here's a deployment yaml with the appropriate image reference to the kbates EG image ^^:
[enterprise-gateway.yaml](https://github.com/jupyter/enterprise_gateway/files/2784153/enterprise-gateway.yaml.txt) (remove `.txt` suffix)


Spark images contain a version of 3.0.0.SNAPSHOT as of commit hash: https://github.com/apache/spark/commit/4c1cd809f812fbd208bf09c5f4d92641ecd17605
[elyra/spark:v3.0.0.4c1cd80](https://cloud.docker.com/u/elyra/repository/docker/elyra/spark)
[elyra/spark-py:v3.0.0.4c1cd80](https://cloud.docker.com/u/elyra/repository/docker/elyra/spark-py)
[elyra/spark-r:v3.0.0.4c1cd80](https://cloud.docker.com/u/elyra/repository/docker/elyra/spark-r)

_(I know, the tags aren't consistent. :smile:)_

**Comment by kevin-bates** [comment]
Here's the Spark JIRA that must be in a release (looks like 3.0) before we can merge: https://issues.apache.org/jira/browse/SPARK-24434?jql=project%20%3D%20SPARK%20AND%20text%20~%20%2224434%22%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/scalable-enterprise-gateway/2014/2

**Comment by kevin-bates** [comment]
Now that Spark 3.0 is available, I've removed the Spark dependency indicator.

**Comment by kevin-bates** [comment]
Cherry-picked the commits in #867 and will close that PR.

**Comment by kevin-bates** [comment]
Thanks for the updates @lresende!

**Comment by tahesse** [comment]
Any chance to parametrize the Scala version during make? Or is this something you don't want?
I can try to lend a hand as well with this.

**Comment by kevin-bates** [comment]
> Any chance to parametrize the Scala version during make? Or is this something you don't want?
I can try to lend a hand as well with this.

Thank you for this offer @tahesse - that is much appreciated.

One thing we've tried to emphasize with respect to the kernelspec examples we provide is that they are just that _examples_.  My concern with introducing this form of _build parameterization_ is that it multiplies the support matrix.  However, I believe what you're suggesting isn't necessarily to create additional example kernel specifications, but merely to ease the ability with which a user can build a Scala kernel launcher for, say, 2.11.  So, in that respect, I think that would be helpful.

What do others think?  @lresende, @rahul26goyal, etc.

Since this particular PR is approaching its 2-year mark (!), I guess I'd be inclined to provide the parameterization is a follow-on PR, but, then again, what's a little longer.

Would you mind proceeding on a branch of this branch and we can make that call in the next day or so?  I know @rahul26goyal wanted to take a closer look at this PR, so that may buy some time.

**Comment by tahesse** [comment]
> However, I believe what you're suggesting isn't necessarily to create additional example kernel specifications, but merely to ease the ability with which a user can build a Scala kernel launcher for, say, 2.11. So, in that respect, I think that would be helpful.

Exactly, so I can host my own EG images as part of my company Artifact repository or OSS project.

**Pull request merged**
